# Generated by Django 4.1.6 on 2023-02-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "movies_list",
            "0005_review_rating_alter_movie_genre_alter_movie_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="user",
        ),
    ]
